### ISSUE TITLE
There's only one GPU，How should I change it？about bash scripts/run_main_ens_fea_dist.sh

### ISSUE THREAD

**Issue by SuperCarryFu** [Equationliu/GA-Attack#1]

**Comment by Equationliu** [comment]
```
CUDA_ID="0"
batch_size=10
NPROC=1
```
and keep all other settings unchanged.

**Comment by SuperCarryFu** [comment]
thank you



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 20, 2022 11:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Equationliu/GA-Attack] There's only one GPU，How should I change it？about bash scripts/run_main_ens_fea_dist.sh (Issue #1)




 CUDA_ID="0" batch_size=10 NPROC=1  
and keep all other settings unchanged.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
